/**
 * LISA Export Manager
 * Handles exporting conversations to multiple formats
 * v0.49-beta
 */

class ExportManager {
  constructor() {
    this.formats = ['json', 'markdown', 'txt'];
  }

  /**
   * Export conversation to specified format
   */
  async export(conversation, format = 'json') {
    const content = await this.getContent(conversation, format);
    const extension = this.getExtension(format);
    const mimeType = this.getMimeType(format);
    const platform = conversation.metadata?.platform || 'conversation';
    const filename = `LISA-${platform}-${Date.now()}.${extension}`;
    
    return {
      content,
      mimeType,
      filename,
      extension,
      format
    };
  }

  /**
   * Get content for specified format
   */
  async getContent(conversation, format = 'json') {
    switch (format.toLowerCase()) {
      case 'markdown':
      case 'md':
        return this.toMarkdown(conversation);
      
      case 'txt':
      case 'text':
        return this.toText(conversation);
      
      case 'json':
      default:
        return this.toJSON(conversation);
    }
  }

  /**
   * Convert conversation to Markdown format
   */
  toMarkdown(conversation) {
    const { metadata, messages } = conversation;
    
    let markdown = `# ${metadata.title || 'AI Conversation'}\n\n`;
    markdown += `**Platform:** ${metadata.platform || 'Unknown'}\n`;
    markdown += `**Date:** ${new Date(metadata.timestamp).toLocaleString()}\n`;
    markdown += `**Messages:** ${messages.length}\n\n`;
    markdown += `---\n\n`;
    
    messages.forEach((msg, index) => {
      const role = msg.role === 'user' ? '👤 User' : '🤖 Assistant';
      markdown += `## ${role}\n\n`;
      markdown += `${msg.content}\n\n`;
      
      if (index < messages.length - 1) {
        markdown += `---\n\n`;
      }
    });
    
    markdown += `\n---\n\n`;
    markdown += `*Generated by LISA Core v${metadata.lisaVersion || '0.49-beta'}*\n`;
    
    return markdown;
  }

  /**
   * Convert conversation to plain text format
   */
  toText(conversation) {
    const { metadata, messages } = conversation;
    
    let text = `AI Conversation\n`;
    text += `${'='.repeat(50)}\n\n`;
    text += `Platform: ${metadata.platform || 'Unknown'}\n`;
    text += `Date: ${new Date(metadata.timestamp).toLocaleString()}\n`;
    text += `Messages: ${messages.length}\n\n`;
    text += `${'='.repeat(50)}\n\n`;
    
    messages.forEach((msg, index) => {
      const role = msg.role === 'user' ? 'USER' : 'ASSISTANT';
      text += `[${role}]\n`;
      text += `${msg.content}\n\n`;
      
      if (index < messages.length - 1) {
        text += `${'-'.repeat(50)}\n\n`;
      }
    });
    
    text += `\n${'='.repeat(50)}\n`;
    text += `Generated by LISA Core v${metadata.lisaVersion || '0.49-beta'}\n`;
    
    return text;
  }

  /**
   * Convert conversation to JSON format (existing LISA format)
   */
  toJSON(conversation) {
    return JSON.stringify(conversation, null, 2);
  }

  /**
   * Get file extension for format
   */
  getExtension(format) {
    switch (format.toLowerCase()) {
      case 'markdown':
      case 'md':
        return 'md';
      case 'txt':
      case 'text':
        return 'txt';
      case 'json':
      default:
        return 'json';
    }
  }

  /**
   * Get MIME type for format
   */
  getMimeType(format) {
    switch (format.toLowerCase()) {
      case 'markdown':
      case 'md':
        return 'text/markdown';
      case 'txt':
      case 'text':
        return 'text/plain';
      case 'json':
      default:
        return 'application/json';
    }
  }

  /**
   * Download conversation in specified format
   */
  async download(conversation, format = 'json', filename = null) {
    const content = await this.export(conversation, format);
    const extension = this.getExtension(format);
    const mimeType = this.getMimeType(format);
    
    const defaultFilename = filename || `LISA-${conversation.metadata.platform || 'conversation'}-${Date.now()}.${extension}`;
    
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    
    // Download using Chrome downloads API
    chrome.downloads.download({
      url: url,
      filename: defaultFilename,
      saveAs: false
    }, (downloadId) => {
      console.log('[LISA Export] Downloaded:', downloadId);
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    });
    
    return { success: true, format, filename: defaultFilename };
  }
}

// Export for use in extension
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ExportManager;
}
